export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR= 'AJAX_ERROR';

export const FETCH_PLAYERSFORSALECOUNT_SUCCESS = 'FETCH_PLAYERSFORSALECOUNT_SUCCESS';
export const FETCH_PLAYERSFORSALEPERPAGE_SUCCESS = 'FETCH_PLAYERSFORSALEPERPAGE_SUCCESS';
export const FETCH_PLAYERSCOUNT_SUCCESS = 'FETCH_PLAYERSCOUNT_SUCCESS';
export const FETCH_PLAYERSPERPAGE_SUCCESS = 'FETCH_PLAYERSPERPAGE_SUCCESS';
export const FETCH_PLAYERINFO_SUCCESS = 'FETCH_PLAYERINFO_SUCCESS';
export const FETCH_PLAYERSPERUSER_SUCCESS = 'FETCH_PLAYERSPERUSER_SUCCESS';
export const FETCH_LOGGEDINUSERPLAYERS_SUCCESS = 'FETCH_LOGGEDINUSERPLAYERS_SUCCESS';

export const FETCH_USERUSERNAMES_SUCCESS = 'FETCH_USERUSERNAMES_SUCCESS';
export const FETCH_USERINFO_SUCCESS = 'FETCH_USERINFO_SUCCESS';
export const FETCH_USERSPERPAGE_SUCCESS = 'FETCH_USERSPERPAGE_SUCCESS';
export const FETCH_USERSCOUNT_SUCCESS = 'FETCH_USERSCOUNT_SUCCESS';

